print("##########################")
print("#                        #")
print("# Vivaldi Fachmy Fahlevi #")
print("#     2510817210017      #")
print("#                        #")
print("##########################")